[target.'cfg(all())']
rustflags = [
    "-Dwarnings",
    "-Dclippy::all",
    "-Dclippy::pedantic",
    "-Aclippy::similar_names",
    "-Aclippy::too_many_arguments",
    "-Aclippy::type_complexity",
    "-Dclippy::needless_pass_by_value",
    "-Dclippy::redundant_allocation",
    "-Dclippy::unused_async",
    "-Dclippy::significant_drop_tightening",
    # Additional rules for your web project
    "-Dclippy::expect_used",
    "-Dclippy::unwrap_used",
    "-Dclippy::await_holding_lock",
    "-Dclippy::expect_used",
    "-Dclippy::unwrap_used",
    "-Dclippy::unnecessary_unwrap",
]
[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = [
    "-C",
    "link-arg=--ld-path=/usr/bin/mold",
    "--cfg",
    "erase_components",
]

[target.wasm32-unknown-unknown]
rustflags = ["--cfg", "erase_components"]
